barkely_hide_bones: 117
cherokee_easy_tee_shirt: 61
clorox_utility_brush: 144
cloud_b_plush_bear: 32
command_hooks: 77
cool_shot_glue_sticks: 62
crayola_24_ct: 130
creativity_chenille_stems: 99
dasani_water_bottle: 499
dove_beauty_bar: 122
dr_browns_bottle_brush: 78
easter_turtle_sippy_cup: 135
elmers_washable_no_run_school_glue: 147
expo_dry_erase_board_eraser: 21
fiskars_scissors_red: 25
fitness_gear_3lb_dumbbell: 1379
folgers_classic_roast_coffee: 401
hanes_tube_socks: 432
i_am_a_bunny_book: 112
jane_eyre_dvd: 77
kleenex_paper_towels: 319
kleenex_tissue_box: 168
kyjen_squeakin_eggs_plush_puppies: 53
laugh_out_loud_joke_book: 78
oral_b_toothbrush_green: 18
oral_b_toothbrush_red: 18
peva_shower_curtain_liner: 250
platinum_pets_dog_bowl: 39
rawlings_baseball: 145
rolodex_jumbo_pencil_cup: 95
safety_first_outlet_plugs: 39
scotch_bubble_mailer: 19
scotch_duct_tape: 142
soft_white_lightbulb: 72
staples_index_cards: 119
ticonderoga_12_pencils: 86
up_glucose_bottle: 272
womens_knit_gloves: 32
woods_extension_cord: 135
