barkely_hide_bones:
  suction: 1
  pinch: 2
cherokee_easy_tee_shirt:
  suction: 1
  pinch: 1
clorox_utility_brush:
  suction: 2
  pinch: 2
cloud_b_plush_bear:
  suction: 1
  pinch: 1
command_hooks:
  suction: 1
  pinch: 3
cool_shot_glue_sticks:
  suction: 1
  pinch: 2
crayola_24_ct:
  suction: 1
  pinch: 3
creativity_chenille_stems:
  suction: 1
  pinch: 2
dasani_water_bottle:
  suction: 2
  pinch: 2
dove_beauty_bar:
  suction: 1
  pinch: 3
dr_browns_bottle_brush:
  suction: 2
  pinch: 2
easter_turtle_sippy_cup:
  suction: 2
  pinch: 2
elmers_washable_no_run_school_glue:
  suction: 1
  pinch: 3
expo_dry_erase_board_eraser:
  suction: 1
  pinch: 3
fiskars_scissors_red:
  suction: 1
  pinch: 3
fitness_gear_3lb_dumbbell:
  suction: 3
  pinch: 2
folgers_classic_roast_coffee:
  suction: 2
  pinch: 2
hanes_tube_socks:
  suction: 2
  pinch: 3
i_am_a_bunny_book:
  suction: 1
  pinch: 3
jane_eyre_dvd:
  suction: 1
  pinch: 3
kleenex_paper_towels:
  suction: 2
  pinch: 2
kleenex_tissue_box:
  suction: 1
  pinch: 3
kyjen_squeakin_eggs_plush_puppies:
  suction: 3
  pinch: 1
laugh_out_loud_joke_book:
  suction: 1
  pinch: 3
oral_b_toothbrush_green:
  suction: 1
  pinch: 3
oral_b_toothbrush_red:
  suction: 1
  pinch: 3
peva_shower_curtain_liner:
  suction: 2
  pinch: 3
platinum_pets_dog_bowl:
  suction: 1
  pinch: 3
rawlings_baseball:
  suction: 1
  pinch: 3
rolodex_jumbo_pencil_cup:
  suction: 3
  pinch: 2
safety_first_outlet_plugs:
  suction: 2
  pinch: 3
scotch_bubble_mailer:
  suction: 1
  pinch: 3
scotch_duct_tape:
  suction: 3
  pinch: 2
soft_white_lightbulb:
  suction: 1
  pinch: 2
staples_index_cards:
  suction: 1
  pinch: 3
ticonderoga_12_pencils:
  suction: 2
  pinch: 3
up_glucose_bottle:
  suction: 1
  pinch: 2
womens_knit_gloves:
  suction: 1
  pinch: 1
woods_extension_cord:
  suction: 1
  pinch: 2
